version: '3.3'
services:
    existdb:
        ports:
          - '9010:8080'
          - '9011:8443'
        container_name: existdb
        image: 'existdb/existdb:latest'
    mongodb:
        image: mongo
        restart: always
        ports:
          - '9020:27017'
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
    mysql:
        image: mysql:5.6
        container_name: mysql_container 
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_container
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        restart: always
        ports:
            - 8080:80
