version: '3.3'
services:
    mysql:
        image: mysql:5.6
        container_name: mysql_container 
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_container
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        restart: always
        ports:
            - 8080:80
